#!/bin/bash
if [ `whoami` != "root" ] ; then
	exec sudo $0 $*
fi

# check arguments
if [ $# != 1 ] ; then
	echo "Usage: $0 [true/false]"
	exit
fi

# activate one variation of the config
if [ $1 == "true" ] ; then
	a2dissite civicboom.com-live
	a2ensite civicboom.com-down
else
	a2dissite civicboom.com-down
	a2ensite civicboom.com-live
fi

# tell apache to check the new version
apache2ctl -t && invoke-rc.d apache2 reload
