#!/usr/bin/env python

import sys

for line in file(sys.argv[1]):
    (lat, lon, name, size) = line.strip().split("\t")
    print "INSERT INTO places(location, name, type)",
    print "VALUES(ST_Point(%s, %s), '%s', '%s');" % (lat, lon, name.replace("'", "\\'"), size)
