#!/usr/bin/env python

import os
import sys
import cloudfiles
import optparse
import fnmatch
from ConfigParser import SafeConfigParser

import logging
logging.basicConfig(
    level   = logging.INFO,
    format  = "%(asctime)s %(levelname)-5.5s %(message)s",
    datefmt = "%H:%M:%S"
)
log = logging.getLogger(__name__)

if __name__ == "__main__":
    option_parser = optparse.OptionParser()
    option_parser.add_option('--ini',
        help='INI file to use for pylons settings',
        type='str', default='development.ini')
    options, args = option_parser.parse_args()

    c = SafeConfigParser()
    c.read(options.ini)

    log.info("Connecting to cloudfiles")
    conn = cloudfiles.get_connection(
        c.get("app:main", "api_key.rs.username"),
        c.get("app:main", "api_key.rs.api_key"),
        authurl = 'https://lon.auth.api.rackspacecloud.com/v1.0'
    )
    cont = conn.get_container('static')
    cont.make_public(ttl=60*60*24*365*2)
