#!/usr/bin/env python

import babel.messages.pofile as po
import sys

def trans(text):
    text = text.replace("_site_name", "Civicboom")
    text = text.replace("_tagline", "News. Don't just read it. Feed it.")
    text = text.replace("_site_description", "Building the world's first true community and audience assignment system")

    words = [
        ("assignment", "request"),
        ("article",    "content"),
        ("reporter",   "user"),
        ("report",     "content"),
        ("group",      "group"),
    ]
    for w, r in words:
        text = text.replace("_"+w, r)
        text = text.replace("_"+w.capitalize(), r.capitalize())
        text = text.replace("_"+w.upper(), r.upper())

    return text


cat = po.read_po(file(sys.argv[1], "r"))

for n, msg in enumerate(cat):
    if n % 10 == 0:
        #print "\rParsing message %d" % n,
        print ".",
#    print msg.id
#    print msg.string
#    print
    if type(msg.id) == tuple:
        msg.string = tuple([trans(i) for i in msg.id])
    else:
        msg.string = trans(msg.id)
print

po.write_po(file(sys.argv[1], "w"), cat)
