#!/bin/sh
if [ `whoami` != "root" ] ; then
	exec sudo $0 $*
fi

cd /opt/cb/share/website/

# only stop if running
if paster serve --status --pid-file=/tmp/cb-website.pid development.ini ; then
	paster serve --daemon \
		--pid-file=/tmp/cb-website.pid \
		--log-file=/tmp/cb-website.log \
		development.ini stop
else
	true
fi

