#!/bin/sh
if [ `whoami` != "root" ] ; then
	exec sudo $0 $*
fi

apt-get update
apt-get install cb-website
/etc/init.d/apache2 reload
echo -n "Active website version: "
dpkg -l cb-website | grep -oE "0.[0-9\.]+"
