#!/bin/bash -e

. /usr/share/debconf/confmodule

if [ "$1" = "configure" ] || [ "$1" = "reconfigure" ] ; then
  db_input high cb-website-api/db_main || true
  db_go
  db_input high cb-website-api/db_geo || true
  db_go
  db_input high cb-website-api/db_log || true
  db_go
  db_input high cb-website-api/mc_session || true
  db_go
  db_input high cb-website-api/mc_cache || true
  db_go
  db_input high cb-website-api/worker_queue || true
  db_go
fi
