#!/bin/sh

. /usr/share/debconf/confmodule

if [ ! -d /tmp/cb-website-temp ] ; then
	mkdir /tmp/cb-website-temp
	chown www-data:www-data /tmp/cb-website-temp
fi

touch /var/log/civicboom-pylons.log
chown www-data:www-data /var/log/civicboom-pylons.log

if [ "$1" = "configure" ] || [ "$1" = "reconfigure" ] ; then
	db_get cb-website-api/do_timed_tasks
	if [ "$RET" = "false" ] ; then
		rm -f /etc/cron.d/cb-website-api
	fi
fi

db_get cb-website-api/db_main        && DB_MAIN=$RET
db_get cb-website-api/db_geo         && DB_GIS=$RET
db_get cb-website-api/db_log         && DB_LOG=$RET
db_get cb-website-api/mc_session     && MC_SESSION=$RET
db_get cb-website-api/mc_cache       && MC_CACHE=$RET

sed -i "s#DEBCONF_DB_MAIN#$DB_MAIN#"       /opt/cb/share/website/production.ini
sed -i "s#DEBCONF_DB_GIS#$DB_GIS#"         /opt/cb/share/website/production.ini
sed -i "s#DEBCONF_DB_LOG#$DB_LOG#"         /opt/cb/share/website/production.ini
sed -i "s#DEBCONF_MC_SESSION#$MC_SESSION#" /opt/cb/share/website/production.ini
sed -i "s#DEBCONF_MC_CACHE#$MC_CACHE#"     /opt/cb/share/website/production.ini

update-rc.d cb-website defaults
invoke-rc.d cb-website start || invoke-rc.d cb-website restart || true

cd /opt/cb/share/website
find -name "*.pyc" | xargs rm -f

#echo "Copying static data to S3"
#/opt/cb/bin/cb-task sync_public_to_warehouse >/dev/null

db_stop
