#!/bin/sh

if [ ! -d /tmp/cb-website-temp ] ; then
	mkdir /tmp/cb-website-temp
	chown www-data:www-data /tmp/cb-website-temp
fi

if [ ! -d /var/log/civicboom ] ; then
	mkdir /var/log/civicboom
	chown www-data:www-data /var/log/civicboom
fi

initctl stop cb-website || true
initctl stop cb-worker  || true

rm -f `find /tmp/cb-website-data/templates -name "*.mako.*"`

initctl start cb-website || true
initctl start cb-worker  || true

cd /opt/cb/share/website
find -name "*.pyc" | xargs rm -f
