#!/bin/sh

if [ ! -d /tmp/cb-website-temp ] ; then
	mkdir /tmp/cb-website-temp
	chown www-data:www-data /tmp/cb-website-temp
fi

update-rc.d cb-website defaults
invoke-rc.d cb-website start

cd /opt/cb/share/website
find -name "*.pyc" | xargs rm -f

#echo "Copying static data to S3"
#/opt/cb/bin/cb-task sync_public_to_warehouse >/dev/null
