#!/bin/sh

mkdir -p /var/log/apache2/civicboom.com/
make-ssl-cert generate-default-snakeoil

ln -s /etc/nginx/sites-available/civicboom.com /etc/nginx/sites-enabled/

mkdir /var/log/civicboom
chown www-data:www-data /var/log/civicboom

update-rc.d cb-website defaults
invoke-rc.d cb-website start
invoke-rc.d nginx restart
