#!/bin/sh

. /usr/share/debconf/confmodule

ln -sf /etc/nginx/sites-available/civicboom.com /etc/nginx/sites-enabled/
ln -sf /etc/nginx/sites-available/static.civicboom.com /etc/nginx/sites-enabled/
rm -f /etc/nginx/sites-enabled/default

if [ "$1" = "configure" ] || [ "$1" = "reconfigure" ] ; then
	db_get cb-website-web/backends && backends=$RET
	cat >/tmp/update_backends <<EOD
import sys

out = []
mode = "cat"
for line in file(sys.argv[1]):
	line = line.strip("\\n")
	if mode == "cat":
		if "### START MANAGED BY DEBCONF" in line:
			mode = "replace"
		out.append(line)
	if mode == "replace":
		for server in sys.argv[2:]:
			out.append("\\tserver "+server+";")
		mode = "findend"
	if mode == "findend":
		if "### END MANAGED BY DEBCONF" in line:
			mode = "cat"
			out.append(line)

file(sys.argv[1], "w").write("\\n".join(out)+"\\n")
EOD
	python /tmp/update_backends /etc/nginx/sites-available/civicboom.com $backends
	rm -f /tmp/update_backends

	db_get cb-website-web/caching
	if [ "$RET" = "false" ] ; then
		cat /etc/nginx/sites-available/civicboom.com | grep -v "DC_CACHING" > /tmp/uncached
		mv /tmp/uncached /etc/nginx/sites-available/civicboom.com
	fi

	db_get cb-website-web/timing
	if [ "$RET" = "false" ] ; then
		cat /etc/nginx/sites-available/civicboom.com | grep -v "DC_TIMING" > /tmp/uncached
		mv /tmp/uncached /etc/nginx/sites-available/civicboom.com
	fi
fi

invoke-rc.d nginx restart

db_stop
