#!/bin/sh

ln -sf /etc/nginx/sites-available/civicboom.com /etc/nginx/sites-enabled/
rm -f /etc/nginx/sites-enabled/default

if [ ! -d /var/log/civicboom ] ; then
	mkdir /var/log/civicboom
	chown www-data:www-data /var/log/civicboom
fi

invoke-rc.d nginx restart

